local AssetsConfig = {
    downloadUrl = "https://raw.githubusercontent.com/penguin-3/file-manager/refs/heads/main/",
    folder = "Juju",
    subfolders = {
        Assets = {
            Images = {
                "Sunrise.png",
                "Scope.png",
                "Glow.png",
                "Target.png",
                "Globe.png",
                "Dropdown.png",
            },
            Sounds = {},
            Fonts = {
                "Menu-Semibold.ttf",
                "Menu-Bold.ttf"
            }
        },
        Configs = {},
    },
}

return AssetsConfig